"""empty message

Revision ID: abf2a3720c04
Revises: 
Create Date: 2020-11-21 01:48:20.695947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'abf2a3720c04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('actors', 'gender',
               existing_type=sa.VARCHAR(length=26),
               nullable=False)
    op.alter_column('actors', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('movies', 'release_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('movies', 'title',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.drop_constraint('movies_actor_id_fkey', 'movies', type_='foreignkey')
    op.drop_column('movies', 'actor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('movies_actor_id_fkey', 'movies', 'actors', ['actor_id'], ['id'])
    op.alter_column('movies', 'title',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('movies', 'release_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('actors', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('actors', 'gender',
               existing_type=sa.VARCHAR(length=26),
               nullable=True)
    op.alter_column('actors', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
